# -*- coding: utf-8 -*-
"""Solution 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Mw0OEXUwCP93jhndaaDxbtCZwSsplR3

**GDSC AI/ML Challenge**
"""

#Importing Libraries
import pandas as pd
import requests

#Getting dataset from Github
url = 'https://raw.githubusercontent.com/GDSC-NMIMS-MPSTME-Mumbai/AI-Recruitment-Task-22/49b07b1dce2c660f47ff37dce55790d16a5b4b91/titanic.csv'
res = requests.get(url, allow_redirects=True)
with open('titanic.csv','wb') as file:
    file.write(res.content)
    
df= pd.read_csv('titanic.csv')

df

#Displaying only the numic values in the dataset
df1 = df._get_numeric_data()

df1.head()

#Removing Null Values from Age and Fare columns in the dataframe
df2 = df.dropna(subset=['Age','Fare'])

df2

#Replacing the null values in Age and Fare with the respective column means

df3 = df

mean_age = df3['Age'].mean()

df3['Age'].fillna(value=mean_age, inplace=True)

mean_fare = df3['Fare'].mean()

df3['Fare'].fillna(value=mean_fare, inplace=True)

df3